### ISSUE TITLE
Need help to get an RC522 work with a teensy 3.2

### ISSUE THREAD

**Issue by sdierick** [sumotoy/RFID#1]
Hello,

I'm just trying to make your library work with my teensy but no way...
If you're still listening any help would be greatly appreciated :)

With your lib deployed, nothing works...
I've tried to printout traces from inside your lib and it seems to me that any aptempt to read any of the RFID register returns FF instead of correct value... 
Could you help me please?

Rgds

**Comment by sumotoy** [comment]
Can you post or give me more info about your RFID module?
I've just tested here with mine and works as expected...

**Comment by sdierick** [comment]
Hello Sumotoy! Nice to hear from you so soon! Sure you'll help me in my struggle ;)

My Module is a basic RFID RC522, 
![img_20160301_110552](https://cloud.githubusercontent.com/assets/17349982/13423991/67a7d678-df9e-11e5-9b52-bc3ac1417c79.jpg)

Just plugged on teensy 3.2 on a breadboard with nothing else

![img_20160301_110618](https://cloud.githubusercontent.com/assets/17349982/13424012/7cc24836-df9e-11e5-87d5-9ff2f62fa243.jpg)

MISO/MOSI/SCK attached to the teensy physical SPI, RST and SS attached to 9 and 10

Nothing works with your exemple code. I get a "waiting for tag or card" even if I show an RFID tag to the reade (both RFIF tag and reader had beed tested OK with balboa's library on Arduino Micro).

I've tried to enter your code and read a particular register on the RC522 and I always get a 255 (atempting  uint8_t value = readMFRC522(Status2Reg); for exemple).

I'm a bit stuck to tell you the truth.
I don't need much, just to return the UID of a Mifare tag. No writing to the tag or crypto or auth issue...

If you explain me how your teensy works with your RFID module and your code, I suppose that could be enough for me?

Thanks a lot!

**Comment by sumotoy** [comment]
Tested again, with 3.0 and 3.2, cannot reproduce your issue!
connections
RFID-----------------Teensy
mosi --------------> 11
miso --------------> 12
sclk  --------------> 13
SDA(aka SS) ---->10
RST -------------->  9
gnd --------------> gnd
+3v3--------------> +3V3

Tested with 5 different RFID, result example
![b](https://cloud.githubusercontent.com/assets/1028096/13441434/6b068234-dff7-11e5-8fc3-ead67d9351ed.jpg)
![a](https://cloud.githubusercontent.com/assets/1028096/13441440/748b55be-dff7-11e5-8d1b-6c9aa39adca4.jpg)

**Comment by sumotoy** [comment]
I just see that Miguel Balboa updated his library:
https://github.com/miguelbalboa/rfid
It include Teensy as well, when I wrote this library was old and long time not maintained but now seems alive, did you try it?

**Comment by sdierick** [comment]
Hello Sumotoy!
Thanks for your support! I've tried again with the official library and it works now. (despite the hours I've spent unsuccessfully, I'm still unable to locate my initial mistake... But it works now and that's the most important)
Thanks for your kind help!

Stephane
